In [2]:
#WEEK 3 OF INTERMEDIATE CONCEPT OF PYTHON

In [1]:
#1... write a python OOP program to get a number from user to display its table

class Table:
    def getNum(self):
        self.num=int(input("Enter a number"))
    def showtable(self):
        for i in range(1,13):
            print(str(i) + " * " + str(self.num) + " = " + str(i * self.num))

obj=Table()
obj.getNum()
obj.showtable()


Enter a number 6


1 * 6 = 6
2 * 6 = 12
3 * 6 = 18
4 * 6 = 24
5 * 6 = 30
6 * 6 = 36
7 * 6 = 42
8 * 6 = 48
9 * 6 = 54
10 * 6 = 60
11 * 6 = 66
12 * 6 = 72


In [1]:
#2...write a python program to get 5 number from user to store in a list, display all number with power of 3 using list comprehension
numbers=[ ]
for i in range(5):
    numbers.append(int(input("Enter a number")))
print(numbers)

cube=[ ]
cube=[number**3 for number in numbers]
print(f"The power of 3 of the list = {cube}")



Enter a number 4
Enter a number 5
Enter a number 6
Enter a number 7
Enter a number 8


[4, 5, 6, 7, 8]
The power of 3 of the list = [64, 125, 216, 343, 512]


In [48]:
#3... write a numpy program to create a two-dimensional array and multiply with any number to that array element. that number 
#should be taken from user

import numpy as np
ar=np.array([[1,2,3], [4,5,6],[1,3,5]])
print(ar)

#get number from user
item = int(input("Enter a number"))

#multiply number with array
new_array = item*ar
print(new_array)

[[1 2 3]
 [4 5 6]
 [1 3 5]]


enter a number 5


[[ 5 10 15]
 [20 25 30]
 [ 5 15 25]]


In [6]:
#4... write a python program to make use of isidentifier method with string

#get an identifier from user
identifier=input("enter a number")
if identifier.isidentifier():
    print(f"value is valid")
else:
    print(f"value not valid")

enter a number wal23


value is valid


In [21]:
#5... write a python program to convert a given array to a list

import numpy as np
ar1=np.array([[2,4,6],[8,10,12],[14,16,18]])
print(ar1)

new_array=[ ]

for i in ar1:
    new_array.append(i)
print(new_array)    



[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[array([2, 4, 6]), array([ 8, 10, 12]), array([14, 16, 18])]


In [3]:
#6...write a python program to create a dictionary from list that display its square as value

#create your list
Numbers=[5,4,3,2,1,6]
square={}
for i in Numbers:
    square[i]= i**2
       
print(f"List with square of list as value = {square}")

List with square of list as value = {5: 25, 4: 16, 3: 9, 2: 4, 1: 1, 6: 36}


In [31]:
#7...write a python program to count total number of lists in a nested list
    
values=[[2,3,4],[3,4,5],[5,6,7],[7,8,9]]

print(f"Number of list in nested list = {len(values)}")


Number of list in nested list = 4


In [6]:
#8...write a python program to get temperature in fahrenheit, to convert into centigrade and kelvin 

f=int(input("Enter value for f"))

      
#k=(f-32)*5/9+273.15

#c=(f-32)*5/9


k = (f-32) * 5/9 + 273.15
c=(f-32)*5/9
print(f"Temperature in fahrenheit to kelvin = {k} ")
print(f"Temperature in fahrenheit to centigrade = {c}")




Enter value for f 78


temperature in fahrenheit to kelvin = 298.7055555555555 
temperature in fahrenheit to centigrade = 25.555555555555557


In [18]:
#9...write a python to access multiple element from a list

item=[2,3,4,5,6,7,3,4,5,6,4,5,6,8,9,4]
access_item=[-1,5,6]

new_item=[item[i] for i in access_item]
print(new_item)

[4, 7, 3]


In [7]:
#10...write a python program to update any value in a dictionary on user request
class_record={'name':['jayjay','nina','vila','cody'],
              'age':[4,6,5,4],
                'best color':['blue','green','yellow','red']}

#change the previous names with new names
class_record['name']=['pop','tom','jin','vail']
print(f"class_record = {class_record}")

class_record = {'name': ['pop', 'tom', 'jin', 'vail'], 'age': [4, 6, 5, 4], 'best color': ['blue', 'green', 'yellow', 'red']}


In [28]:
#11... write a python program to convert dictionary keys and values into two list one list should store keys and the other list should store values
class_record={'name':['jayjay','nina','vila','cody'],
              'age':[4,6,5,4],
                'best color':['blue','green','yellow','red']}
#sstore all the keys in a list
new_key=[ ]
for key in class_record.keys():
    new_key.append(key)
    print(f"all keys = {new_key}")

#store all values in a list
new_value=[ ]
for value in class_record.values():
    new_value.append(value)
    print(f"all values = {new_value}")


all keys = ['name']
all keys = ['name', 'age']
all keys = ['name', 'age', 'best color']
all values = [['jayjay', 'nina', 'vila', 'cody']]
all values = [['jayjay', 'nina', 'vila', 'cody'], [4, 6, 5, 4]]
all values = [['jayjay', 'nina', 'vila', 'cody'], [4, 6, 5, 4], ['blue', 'green', 'yellow', 'red']]


In [18]:
#12... write a python program to add two array
arr1=[1,2,3]
arr2=[4,5,6]
result=arr1+arr2
#print(result)

result=[x+y for x,y in zip(arr1,arr2)]
print(f"arr1 + arr2 = {result}")

arr1 + arr2 = [5, 7, 9]


In [19]:
#13...write a python program to find most occuring element in a given list  of numbers

from collections import Counter
numbers=[2,3,4,5,6,7,8,3,4,5,2,3,4,5,6,4,1,4,9,4]

common_element = Counter(numbers)
most_freq=max(common_element, key=common_element.get)
print(f"Most occuring element in the list = {most_freq}")



Most occuring element in the list = 4


In [21]:
#14...write a python program to filter odd number from a given dictionary keys, display only those values which have odd keys
names={1:'funnybone',2:'clint de drunk', 3:'brain jotter', 4:'wisabi',5:'arrangee'}
print(lst)

for key, value in names.items():
    if key%2!=0:
        print(value)


{1: 'funnybone', 2: 'clint de drunk', 3: 'brain jotter', 4: 'wisabi', 5: 'arrangee'}
funnybone
brain jotter
arrangee


In [87]:
#15... write a python program to get the total length of all keys of a dictionary with string keys 
commedy={'one':'funnybone','two':'clint de drunk', 'three':'brain jotter', 'four':'wisabi', 'ten':'who'}


s1=0
for key in commedy.keys():
    print(key)
    s1 += len(key)

print(s1)

    

one
two
three
four
ten
18


In [67]:
#### 16...write a python program to convert an array element to boolean value

import numpy as np
arr=np.array([[1,2,3],[8,6,4],[7,8,9]])
print(arr)
bool_arr=arr.astype('bool')
print(bool_arr)


[[1 2 3]
 [8 6 4]
 [7 8 9]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [30]:
#17... write a python program to create a list from existed list that contains uppercase 
commedians=['funnybone','clint de drunk','brain jotter','DADDY WA', 'BASKETMOUTH','wisabi']
new_list=[i for i in commedians
         if i.isupper()]
print(f"Values with uppercase are :{new_list}")

Values with uppercase are :['DADDY WA', 'BASKETMOUTH']


In [32]:
#18... write a python program to create a dicionary  which display those value which have vowel character
commedians={1:'funnybone',2:'clint de drunk',3:'brain jotter',4:'daddy wa', 5:'bsktmth',6:'wisabi'}

for key,value in commedians.items():
    if 'a' in value or 'e' in value or 'i' in value or 'o' in value or 'u' in value:
        print(value)

funnybone
clint de drunk
brain jotter
daddy wa
wisabi


In [14]:
#19... write a python program to create an array  of zero according to user entered number

import numpy as np
user_num=int(input("enter a number"))
ar=np.zeros(user_num)
print(ar)

enter a number 5


[0. 0. 0. 0. 0.]


In [61]:
#20...write a python program to get password from the user that contains alphanumeric and more than 8 and less than 
#20 characters

#get password from user
pswd=input("Enter a pwd")

#give condition and print
if (pswd.isalnum()) and len(pswd) < 20 and len(pswd) >8:
    print("pswd is correct")
else:
     print("pswd is incorrect")

Enter a pwd tyr56


pswd is incorrect


In [62]:
#21...write a python program to update any key in a dictionary on user request
class_record={'name':['jayjay','nina','vila','cody'],
              'age':[4,6,5,4],
                'best color':['blue','green','yellow','red']}


class_record['weight']=[12,14,13,15]

print(class_record)

{'name': ['jayjay', 'nina', 'vila', 'cody'], 'age': [4, 6, 5, 4], 'best color': ['blue', 'green', 'yellow', 'red'], 'weight': [12, 14, 13, 15]}


In [1]:
#22...
my_list = [' ']
if my_list==True:
    print("The list is not empty")
else:
    print("The list is empty")
    

The list is empty


In [3]:
#23...
y=(1<2) and (2<3) and (3>4)
print(y)

False


In [70]:
#24...return the longest string in the list of string, if there is a tie, return the string with highest index
names=['love', 'hope', 'peace', 'joy', 'grace']
print(max(names))

peace


In [34]:
#25...Create a guessing game

import random

#declare computer to select a random number 
num=random.randint(1,100)
print("computer selected a number from 1 to 100 (inclusive), now its your turn - ")
turns=0

#input your guesses number
while True:
    guess=int(input("enter the guessed number - "))
    if (guess==num):
        print("\nyou got it right")
        break
#if your number is bigger...
    elif (guess<num):
        print("\n\tbigger number please")
        turns+=1 
#if your number is smaller
    elif (guess>num):
        print("\tsmaller number please")
        turns+=1
#when you finally get it right, declare how many trial it took you
print("number of turns -", turns+1)

computer selected a number from 1 to 100 (inclusive), now its your turn - 


enter the guessed number -  65



	bigger number please


enter the guessed number -  85



	bigger number please


enter the guessed number -  95


	smaller number please


enter the guessed number -  90


	smaller number please


enter the guessed number -  87



	bigger number please


enter the guessed number -  89


	smaller number please


enter the guessed number -  88



you got it right
number of turns - 7
